name: Debug env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  TOK: ${{ secrets.NPM_TOKEN }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: production
    env:
      MY_VAR_REPO: ${{ vars.MYVAR }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo " This token is -->   $TOK   test===> ${{ secrets.MY_TEST_SECRET }}"
      - run: echo " This secreat token is -->   ${{ secrets.NPM_TOKEN }}"
      - run: echo " This test token is -->   ${{ secrets.test }}"
      - run: echo "  vars.MYVAR  -->   ${{ vars.MYVAR }}"
      - run: echo " MYVAR -->   $MY_VAR_REPO"
      - name: Test
        env:
          TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_SECRET: ${{ secrets.test }}
          TEST_NPM: ${{ secrets.NPM_TOKEN }}
        run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#TEST_SECRET}
          echo ${#TEST_NPM}
      - name: Check vars
        run: echo "${{ toJson(vars) }}"
      - name: Check env
        run: echo "${{ toJson(env) }}"    
      - name: View context    
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"